name: Deploy on Main

on:
  push:
    branches:
      - main

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        run: |
          cd /home/ahmad/erpnext/apps/erpnext
          git pull internal main

      - name: Build project
        run: |
          cd /home/ahmad/erpnext
          bench build

      #- name: Update dependencies
      #  run: |
      #    cd /home/ahmad/erpnext
      #    bench update --requirements

      - name: Clear cache for sites
        run: |
          cd /home/ahmad/erpnext
          bench --site all clear-cache
